### ISSUE TITLE
3.0 todo

### ISSUE THREAD

**Issue by azazellochg** [azazellochg/pytemscript#1]
- [x] csa.supportedcameras vs acquisitions.cameras
- [x] add a check when adv scr is not available
- [x] add high-level methods to base_microscope and microscope
- [x] document all changes
- [x] get metadata as dict
- [x] use comtypes
- [x] remote / null server refactor
- [x] sort out mag etc index changes
- [ ] regroup optics?
- [ ] acquire stem series?
- [x] basic LD support
- [x] adv scr "3.0" new functions
